### ISSUE TITLE
Add Model for version number and date, and util functions

### ISSUE THREAD

**Issue by selama1** [aih/billsim#27]
Add a table with run instance info. Each row include id, version and date.

Add for each bill2bill a run instance id.

**Comment by aih** [comment]
- [ ] We need to update [pymodels](https://github.com/aih/billsim/blob/main/src/billsim/pymodels.py) to support version and date. We need a model (`Currency`) with three fields for now: `id`, `date`, `version`.

- [ ] In the BillToBill model, we need to add a foreign key field corresponding to the `id` of the `Currency` model.

**Comment by aih** [comment]
- [ ] Then, we will need to add functions to `db_utils` to save this update information each time we run the tool, and to include the id in any new bill-to-bill and section-to-section rows.

**Comment by aih** [comment]
This is similar to what is done with a `temporal table`, see [Microsoft temporal tables](https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16)

**Comment by aih** [comment]
- [ ] Once the db tables and utils are ready here, we will need to call them as part of the pipeline.

**Comment by aih** [comment]
@selama1 has this been done? Is it obsolete?

**Comment by selama1** [comment]
Yes. This is all done. This is the currency table/currency_id we added.
