### ISSUE TITLE
Issues with running billsim on Python3.8 and Python3.9

### ISSUE THREAD

**Issue by Leschonander** [aih/billsim#28]
I tried running billsim with python3.8 and python3.9, and got two separate issues.

With 3.8
```python
___________ ERROR collecting tests/constants_test.py ___________
tests/constants_test.py:3: in <module>
    from billsim.pymodels import BillPath
src/billsim/pymodels.py:36: in <module>
    class Section(SectionMeta):
src/billsim/pymodels.py:37: in Section
    similar_sections: list[SimilarSection]
E   TypeError: 'type' object is not subscriptable
_____________ ERROR collecting tests/utils_test.py _____________
tests/utils_test.py:9: in <module>
    from billsim.pymodels import BillPath
src/billsim/pymodels.py:36: in <module>
    class Section(SectionMeta):
src/billsim/pymodels.py:37: in Section
    similar_sections: list[SimilarSection]
E   TypeError: 'type' object is not subscriptable
```

With 3.9

```python
from lxml import etree
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so: mach-o, but wrong architecture
        /opt/homebrew/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so: mach-o, but wrong architecture
```

This latter one seems to be a issue with m1 macs from considering the error complains about architecture.

**Comment by aih** [comment]
Ah, on the last one, have you installed Rosetta?

**Comment by aih** [comment]
I installed using a virtualenv of v3.912, and `python setup.py install`. I added pytest and the tests worked:

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/217356/181181655-fea29557-46aa-4334-8e49-e7d08372ce97.png">

**Comment by Leschonander** [comment]
Installed Rosetta, so there is progress on that. Got the following error however
<img width="737" alt="image" src="https://user-images.githubusercontent.com/33600597/181402110-5dc9b7fd-148b-41a5-89dc-ddb587acab19.png">

**Comment by Leschonander** [comment]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/33600597/181402922-b971a220-1db0-47d7-997b-98cf3aeeb178.png">
I think doing something like this may be the trick

**Comment by aih** [comment]
Yes, and also reinstalling from scratch with pip, now that you have Rosetta.

**Comment by Leschonander** [comment]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/33600597/181404045-d52eaeaf-b00b-4abf-9977-1b741fbb39af.png">
What's the archectuciture when you run your commands on the commandline? I have a terminal running with rosetta and trying to check if this is the right uname or not. 

Edit: HMM
Ran `sysctl -n sysctl.proc_translated`. According to this, my regular terminal is running rossetta
https://stackoverflow.com/questions/65984353/how-to-check-if-a-process-is-running-under-rosetta-with-terminal.

And by reinstall from scratch, does this mean reinstalling homebrew + then python + then pip? What's the cleanest way to do that you think? I'm realizing my python installs are a mess (but aren't they for all)

**Comment by aih** [comment]
My laptop is out of commission for a week (MS teams overheated it). We'll schedule a time with Sela and / or Jay

**Comment by Leschonander** [comment]
That's a real pain. This week is rather busy but next week I should have more time in the afternoon barring any sudden surprises for a meeting.

**Comment by Leschonander** [comment]
Via talking to @aih I managed to solve this issue. Main solution is to install virtualenv and brew in User to run python in a architecture that does not break things.
